---
title: "Drydown - Fluxes"
output: github_document
---
Run: `r Sys.Date()`

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>", 
                      fig.path = "images/markdown-picarro/"
                      )

source("0-drydown_functions.R")
picarro = read.csv("data/processed/picarro_processed.csv")

picarro2 = 
    picarro %>% 
    dplyr::mutate(DATETIME2 = ymd_hms(DATETIME)) %>% 
    group_by(Core) %>% 
    dplyr::mutate(elapsed_days = as.double(difftime(DATETIME2, min(DATETIME2), units = "days")))
```


# 1. PICARRO DATA

### individual cores  
```{r co2_flux_cores}
ggplot(picarro2, aes(elapsed_days, flux_co2_umol_g_s*1000, color = Core_assignment)) + 
    geom_point() + geom_line() +
    ylab("flux_co2_nmol_g_s")+
    facet_wrap(~Core)+
    #facet_grid(drying~length, scale = "free_x")+
    geom_hline(yintercept = 0)+
    theme(legend.position="none")
```

### by treatment  
```{r co2_flux_trt}
ggplot(picarro2, aes(elapsed_days, flux_co2_umol_g_s*1000, color = Core_assignment)) + 
    geom_point() + geom_line() +
    ylab("flux_co2_nmol_g_s")+
    facet_grid(drying~length, scale = "free_x")+
    geom_hline(yintercept = 0)+
    theme(legend.position="none")
```

