---
output:
  github_document:
    html_preview: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r knitrsetup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
options(tibble.print_min = 5, tibble.print_max = 5)
library(drake)
library(ggplot2)
theme_set(theme_bw())
library(dplyr)
```

# TES-drydown

Run: `r Sys.Date()`

```{r, echo=FALSE, message=FALSE}
readd("massdata") %>% 
  mutate(Days = as.integer(difftime(Date, min(Date), units = "days"))) %>% 
  arrange(Date) %>% 
  group_by(Core) %>% 
  mutate(change = c(NA, diff(Mass_g) / diff(Days))) ->
  massdata

ggplot(massdata, aes(Days, Mass_g, group = `Core`, color = Length)) +
  geom_point() + geom_line() +
  facet_wrap(~Length, scales = "free_y")

massdata %>% filter(Date == max(Date)) %>% pull(change) -> core_chg
summary(core_chg)
```

Currently cores' median mass change is `r round(median(core_chg), 1)` g/day:

```{r, echo=FALSE}
ggplot(tibble(x = core_chg), aes(x = x)) + 
  geom_histogram(bins = 25) +
  xlab("Mass loss (g) per day")

# table
massdata %>% 
  filter(Date == max(Date)) %>% 
  arrange(desc(abs(change))) %>% 
  select(Date, Core, Mass_g, change) %>% 
  print(n = 100)
```

