---
title: "TES-Drydown"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 300,
                      echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>"
                      )
```

```{r, fig.height=3, fig.width=6}
library(ggplot2)
library(usmap)

test_data <- data.frame(lon = c(-147.487, -123.690), lat = c(65.162,46.308))
transformed_data <- usmap_transform(test_data)
plot_usmap(color = "grey") + 
  geom_point(data = transformed_data, 
             aes(x = lon.1, y = lat.1), 
             color = "black",
             size = 2.5)+
  annotate("text", label = "Secret River (SR)", x = -1686856, y = 411954.3, size=2, hjust="left")+
  annotate("text", label = "Caribou Poker Creeks Research Watershed\n(CPCRW)", x = -1051020, y = -1842646.7, 
           size=2, hjust="left")+
  NULL
  
```

---

<details>
  <summary>Session Info</summary>
  
date: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>
