---
title: "sample_tracking"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,
                      warning=FALSE,
                      collapse = TRUE,
                      include = FALSE,
                      comment = "#>" 
                      #fig.path = "images/markdown-picarro/"
                      )

library(tidyverse)
library(here)
```

```{r}
## comparing sample lists


# 1. which samples have been run for TC-TN? ----
tctn_samples = read.csv(here::here("data/combined_site_tctn.csv")) %>% 
  dplyr::mutate(coreID = str_replace(sample, " 0-5cm",""),
                coreID = str_replace(coreID, " 5-end",""),
                coreID = str_replace(coreID, ", 0-5cm",""),
                coreID = str_replace(coreID, ", 5cm-end",""),
                coreID = str_replace(coreID, ",","")) %>% 
  filter((flag != "skip"))

corekey = read.csv(here::here("data/processed/corekey.csv"))


matched_tctn = 
  corekey %>% 
  left_join(tctn_samples, by = "coreID") %>% 
  dplyr::mutate(tctn_run = !is.na(sample)) %>% 
  filter(!length == "1000 day") %>% 
  dplyr::select(coreID, Core_assignment, sample, tctn_run) %>% 
  distinct(coreID,Core_assignment, tctn_run)

#


```

```{r}
# 2. which samples have been run for POM-non-POM? ----
pom_samples = read.csv(here::here("data/combined_site_pom.csv"))
pom_key = read.csv(here::here("data/pom_key.csv")) %>% 
  dplyr::select(-Sample)

pom_tctn = 
  pom_key %>% 
  left_join(pom_samples, by = "POM_ID") %>% 
  filter(!is.na(C.N..ratio))

matched_pom = 
  corekey %>% 
  left_join(pom_tctn, by = "coreID") %>% 
  dplyr::mutate(pom_run = !is.na(POM_ID)) %>% 
  dplyr::select(coreID, pom_run, POM_ID) %>% 
  distinct(coreID, pom_run)
  
#

```


**Which samples have been run?**

<details>
  <summary>Click to expand</summary>
  
  
1000-day drought samples have been excluded.  
POM needs to be recalculated
```{r, include=T}
# 3. combine all ----
samples_run = 
  left_join(matched_tctn, matched_pom, by = "coreID")

samples_run %>% 
  dplyr::mutate(tctn_run = if_else(tctn_run=="FALSE"," ", as.character(tctn_run))) %>% 
  dplyr::mutate(pom_run = if_else(pom_run=="FALSE"," ", as.character(pom_run))) %>% 
  knitr::kable()
```

</details>

```{r, eval=FALSE}
a = 
  samples_run %>% 
  filter(!Core_assignment %in% c("time0", "Ambient")) %>% 
  separate(Core_assignment, c("site", "duration", "location", "drying", "rep"),
           sep = "_") %>% 
  arrange(site, duration, location, drying, rep) %>% 
  group_by(site, duration, location, drying) %>% 
  mutate(n = n())
```


---

**Which samples should we process for further analyses?**

WEOC/NMR/FTICR analysis  
randomly selecting three replicates per treatment set

```{r, eval=F}
## DON'T RUN THIS AGAIN, BECAUSE THAT WILL CHANGE THE RANDOM LIST OF REPLICATES SELECTED!!!

## cpcrw_selected_replicates = 
##   samples_run %>% 
##   filter(!Core_assignment %in% c("time0", "Ambient")) %>% 
##   separate(Core_assignment, c("Site", "length", "location", "drying", "rep"),
##            sep = "_") %>% 
##   filter(Site=="CPCRW") %>%
##   group_by(Site, length, location, drying) %>% 
##   dplyr::mutate(tctn_run = if_else(tctn_run=="FALSE"," ", as.character(tctn_run))) %>% 
##   dplyr::mutate(pom_run = if_else(pom_run=="FALSE"," ", as.character(pom_run))) %>% 

##   sample_n(3) 
## 
## write.csv(cpcrw_selected_replicates, here::here("data/processed/cpcrw_selected_replicates_for_WEOC.csv"), 
##           row.names = F)
```


```{r, cpcrw_selected_reps, include=TRUE}
options(knitr.kable.NA = '')
read.csv(here::here("data/processed/cpcrw_selected_replicates_for_WEOC.csv")) %>% 
  dplyr::select(-tctn_run,-pom_run) %>% 
  knitr::kable()
```

```{r, eval=F}
## DON'T RUN THIS AGAIN, BECAUSE THAT WILL CHANGE THE RANDOM LIST OF REPLICATES SELECTED!!!

##  some treatments have 4+ replicates, whereas some have <4

##  where reps are 4+, randomly select 3 
##   sr_selected_replicates_1 = 
##     samples_run %>% 
##     filter(!Core_assignment %in% c("time0", "Ambient")) %>% 
##     separate(Core_assignment, c("Site", "length", "location", "drying", "rep"),
##              sep = "_") %>% 
##     filter(Site=="SR") %>%
##     dplyr::mutate(tctn_run = if_else(tctn_run=="FALSE"," ", as.character(tctn_run))) %>% 
##     dplyr::mutate(pom_run = if_else(pom_run=="FALSE"," ", as.character(pom_run))) %>% 
##     group_by(Site, length, location, drying) %>% 
##     dplyr::mutate(n = n()) %>%
##     filter(n>3) %>% 
##     sample_n(3) 

##   # where we have only 2 or 3 replicates, choose all
##   sr_selected_replicates_2 = 
##     samples_run %>% 
##     filter(!Core_assignment %in% c("time0", "Ambient")) %>% 
##     separate(Core_assignment, c("Site", "length", "location", "drying", "rep"),
##              sep = "_") %>% 
##     filter(Site=="SR") %>%
##     dplyr::mutate(tctn_run = if_else(tctn_run=="FALSE"," ", as.character(tctn_run))) %>% 
##     dplyr::mutate(pom_run = if_else(pom_run=="FALSE"," ", as.character(pom_run))) %>% 
##     group_by(Site, length, location, drying) %>% 
##     dplyr::mutate(n = n()) %>%
##     filter(n<4)  

##   sr_selected_replicates_combined = 
##     sr_selected_replicates_1 %>% 
##     rbind(sr_selected_replicates_2) %>% 
##     arrange(Site, length, location, drying)


##    
##    write.csv(sr_selected_replicates_combined, here::here("data/processed/sr_selected_replicates_for_WEOC.csv"), 
##              row.names = F)
```

```{r, sr_selected_reps, include=TRUE}
options(knitr.kable.NA = '')
read.csv(here::here("data/processed/sr_selected_replicates_for_WEOC.csv")) %>% 
  dplyr::select(-n, -tctn_run, -pom_run) %>% 
  knitr::kable()
```


----

<details>
    <summary>Session Info</summary>
    
Last run: `r Sys.Date()`  
```{r, include=TRUE}
sessionInfo()
```

</details>

