---
title: "Untitled"
output: 
  github_document:
  html_preview: true

---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}

pal_saturation = rev(PNWColors::pnw_palette("Sunset2", 3))
theme_set(theme_kp())


targets::tar_load_everything()
```

------

## FTICR

### Stats -- PERMANOVA

```{r icr_permanova}

relabund_wide = 
  fticr_relabund %>% 
  #filter(length != "timezero") %>% 
  ungroup() %>% 
  mutate(Class = factor(Class, 
                        levels = c("aliphatic", "unsaturated/lignin", 
                                   "aromatic", "condensed aromatic"))) %>% 
  dplyr::select(-c(abund, total)) %>% 
  pivot_wider(names_from = "Class", values_from = "relabund") %>% 
  drop_na() %>% 
  #    replace(is.na(.), 0) %>% 
  force()

print("FTICR -- including top and bottom depths")
# permanova_fticr_all = 
  adonis2(relabund_wide %>% dplyr::select(where(is.numeric)) ~ 
            (site+depth+length+saturation+drying), 
          by = "margin",
          data = relabund_wide) %>% broom::tidy()


print("FTICR -- including top depth only")
relabund_wide_surface = relabund_wide %>% filter(depth == "0-5cm")
# permanova_fticr_all = 
  adonis2(relabund_wide_surface %>% dplyr::select(where(is.numeric)) ~ 
            (site+length+saturation+drying), 
          by = "margin",
          data = relabund_wide_surface) %>%  broom::tidy()

```


### Stats -- Clustering and PCA

(surface soils only)

```{r icr_cluster, include=FALSE}
library(cluster)
library(factoextra)


df = relabund_wide_surface %>%  dplyr::select(where(is.numeric))
grp = relabund_wide_surface %>%  dplyr::select(!where(is.numeric))

#fviz_nbclust(df, FUN = hcut, method = "wss")
#fviz_nbclust(df, FUN = hcut, method = "silhouette")
# three clusters

d <- dist(df, method = "euclidean")
hc1 <- hclust(d, method = "complete" )
plot(hc1, cex = 0.6, hang = -1)
hc5 <- hclust(d, method = "ward.D2" )
sub_grp <- cutree(hc5, k = 3)
table(sub_grp)
plot(hc5, cex = 0.6)
rect.hclust(hc5, k = 5, border = 2:5)

df_cl <- mutate(df, cluster = sub_grp) %>% cbind(grp)
count(df_cl,cluster)

  
library(ggpubr)

df_cl %>% 
  filter(site == "Alaska") %>% 
  mutate(drying_saturation = paste0(drying, "-", saturation)) %>% 
  ggdotplot(y = "saturation", x = "cluster", fill = "length", 
            position = position_jitter(0.05), dotsize = 2)+
#  scale_fill_manual(values = c("pink", "red", "lightblue", "blue"))+
  coord_flip()+
  facet_wrap(~depth + saturation, nrow = 1)
  
#  ggplot(aes(y = cluster, x = length, fill = length))+
#  geom_dotplot(binaxis = "y", stackdir = "centerwhole",
#               dotsize = 0.4)+
#  facet_wrap(~depth + saturation + drying, nrow = 1)+
#  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


```{r pca_fn}
fit_pca_function = function(dat){
  
  dat %>% 
    drop_na()
  
  num = 
    dat %>%       
    dplyr::select(where(is.numeric)) %>%
    dplyr::mutate(row = row_number()) %>% 
    drop_na()
  
  num_row_numbers = num %>% dplyr::select(row)
  
  grp = 
    dat %>% 
    dplyr::select(where(is.character)) %>% 
    dplyr::mutate(row = row_number()) %>% 
    right_join(num_row_numbers)
  
  
  num = num %>% dplyr::select(-row)
  pca_int = prcomp(num, scale. = T)
  
  list(num = num,
       grp = grp,
       pca_int = pca_int)
}

```

```{r icr_pca}

#
df_cl = df_cl %>% mutate(cluster = as.character(cluster))


library(ggConvexHull)

pca_cluster = fit_pca_function(df_cl) 

ggbiplot(pca_cluster$pca_int, obs.scale = 1, var.scale = 1,
                 #  groups = as.character(pca_cluster$grp$cluster), 
                   ellipse = T, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_convexhull(aes(group = pca_cluster$grp$cluster, fill = NA), color = "black",
                      #fill = pca_cluster$grp$cluster
                    
                  alpha = 0)+
  geom_point(size=5,stroke=1, alpha = 1,
             aes(shape = pca_cluster$grp$saturation,
                 fill = pca_cluster$grp$length))+ 
  scale_shape_manual(values = c(23, 21, 22))+
  scale_color_manual(values = pnw_palette("Sailboat", 7))+
  scale_fill_manual(values = pnw_palette("Bay", 7))+
  labs(title = "Overall PCA, both regions",
       subtitle = "Surface horizons only")+
  theme_kp()+
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL
  

```


### Van Krevelens
```{r}

```



### Relative abundance

```{r}

```

------

## NMR

### Stats -- PERMANOVA

```{r nmr_permanova}

  nmr_relabund_wide = 
    nmr_relabundance %>% 
    #filter(length != "timezero") %>% 
    ungroup() %>% 
    pivot_wider(names_from = "group", values_from = "relabund") %>% 
    force()
  
  permanova_nmr = 
    adonis2(nmr_relabund_wide %>% dplyr::select(where(is.numeric)) ~ 
              (site+length+saturation+drying), 
            by = "margin",
            data = nmr_relabund_wide)
  broom::tidy(permanova_nmr)

```

### Stats -- PCA and clustering

```{r nmr_cluster, include=FALSE}


  df = nmr_relabund_wide %>%  dplyr::select(where(is.numeric))
  grp = nmr_relabund_wide %>%  dplyr::select(!where(is.numeric))
  
  # fviz_nbclust(df, FUN = hcut, method = "wss")
  # fviz_nbclust(df, FUN = hcut, method = "silhouette")
  # three clusters
  
  d <- dist(df, method = "euclidean")
  hc1 <- hclust(d, method = "complete" )
  plot(hc1, cex = 0.6, hang = -1)
  hc5 <- hclust(d, method = "ward.D2" )
  sub_grp <- cutree(hc5, k = 3)
  table(sub_grp)
  plot(hc5, cex = 0.6)
  rect.hclust(hc5, k = 5, border = 2:5)
  
  df_cl <- mutate(df, cluster = sub_grp) %>% cbind(grp)
  count(df_cl,cluster)
  
  
  
  library(ggpubr)
  
  df_cl %>% 
    filter(site == "Alaska") %>% 
    mutate(drying_saturation = paste0(drying, "-", saturation)) %>% 
    ggdotplot(y = "saturation", x = "cluster", fill = "length", 
              position = position_jitter(0.05), dotsize = 2)+
    #  scale_fill_manual(values = c("pink", "red", "lightblue", "blue"))+
    coord_flip()+
    facet_wrap(~depth + saturation, nrow = 1)
  
  #  ggplot(aes(y = cluster, x = length, fill = length))+
  #  geom_dotplot(binaxis = "y", stackdir = "centerwhole",
  #               dotsize = 0.4)+
  #  facet_wrap(~depth + saturation + drying, nrow = 1)+
  #  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  
  
```

```{r nmr_pca}

  library(ggConvexHull)

 
  df_cl = df_cl %>% mutate(cluster = as.character(cluster))
  df_cl_pca = fit_pca_function(df_cl)


pca_cluster = fit_pca_function(df_cl) 

ggbiplot(pca_cluster$pca_int, obs.scale = 1, var.scale = 1,
                 #  groups = as.character(pca_cluster$grp$cluster), 
                   ellipse = T, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_convexhull(aes(group = pca_cluster$grp$cluster, fill = NA), color = "black",
                      #fill = pca_cluster$grp$cluster
                    
                  alpha = 0)+
  geom_point(size=5,stroke=1, alpha = 1,
             aes(shape = pca_cluster$grp$saturation,
                 fill = pca_cluster$grp$length))+ 
  scale_shape_manual(values = c(23, 21, 22))+
  scale_color_manual(values = pnw_palette("Sailboat", 7))+
  scale_fill_manual(values = pnw_palette("Bay", 7))+
  labs(title = "Overall PCA, both sites",
       subtitle = "Surface horizons only")+
  theme_kp()+
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL
  
  
```

```{r nmr_pca_sites}

pca_cluster = fit_pca_function(df_cl %>% filter(site == "Alaska")) 

ggbiplot(pca_cluster$pca_int, obs.scale = 1, var.scale = 1,
                 #  groups = as.character(pca_cluster$grp$cluster), 
                   ellipse = T, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_convexhull(aes(group = pca_cluster$grp$cluster, fill = NA), color = "black",
                      #fill = pca_cluster$grp$cluster
                    
                  alpha = 0)+
  geom_point(size=5,stroke=1, alpha = 1,
             aes(shape = pca_cluster$grp$saturation,
                 fill = pca_cluster$grp$length))+ 
  scale_shape_manual(values = c(23, 21, 22))+
  scale_color_manual(values = pnw_palette("Sailboat", 7))+
  scale_fill_manual(values = pnw_palette("Bay", 7))+
  labs(title = "Overall PCA, Alaska",
       subtitle = "Surface horizons only")+
  theme_kp()+
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL


# Washington
pca_cluster = fit_pca_function(df_cl %>% filter(site == "Washington")) 

ggbiplot(pca_cluster$pca_int, obs.scale = 1, var.scale = 1,
                 #  groups = as.character(pca_cluster$grp$cluster), 
                   ellipse = T, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_convexhull(aes(group = pca_cluster$grp$cluster, fill = NA), color = "black",
                      #fill = pca_cluster$grp$cluster
                    
                  alpha = 0)+
  geom_point(size=5,stroke=1, alpha = 1,
             aes(shape = pca_cluster$grp$saturation,
                 fill = pca_cluster$grp$length))+ 
  scale_shape_manual(values = c(23, 21, 22))+
  scale_color_manual(values = pnw_palette("Sailboat", 7))+
  scale_fill_manual(values = pnw_palette("Bay", 7))+
  labs(title = "Overall PCA, Washington",
       subtitle = "Surface horizons only")+
  theme_kp()+
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL

```


## NMR relabund


```{r nmr_relabund}

nmr_relabundance %>% 
  filter(site == "Alaska") %>% 
  ggplot(aes(x = coreID, y = relabund, fill = group))+
  geom_bar(stat = "identity")+
  facet_wrap( ~ length + drying + saturation, scale = "free_x")


nmr_relabundance %>% 
  filter(site == "Washington") %>% 
  ggplot(aes(x = coreID, y = relabund, fill = group))+
  geom_bar(stat = "identity")+
  facet_wrap( ~ length + drying + saturation, scale = "free_x")

```

## NMR specctra

```{r nmr_spectra}

nmr_spectra_processed %>% 
  filter(coreID %in% c("C61", "C76", "C81")) %>% 
  nmr_plot_spectra(
    binset = bins_Clemente2012,
    map = aes(group = coreID, x = ppm, y = intensity, color = saturation),
    stagger = 0.4,
    label_position = 2
  )+
  ylim(0, 2.2)+
  scale_color_manual(values = pal_saturation)



nmr_spectra_processed %>% 
  filter(coreID %in% c("S92", "S32", "S53")) %>% 
  nmr_plot_spectra(
    binset = bins_Clemente2012,
    map = aes(group = coreID, x = ppm, y = intensity, color = saturation),
    stagger = 0.4,
    label_position = 2
  )+
  ylim(0, 2.2)+
  scale_color_manual(values = pal_saturation)

```

