---
title: "chemistry_report_NEW"
output: 
  github_document:
  html_preview: true

---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE)
```

```{r}

source("2-code/0-packages.R")
source("2-code/1-functions_processing.R")
library(ggh4x)
theme_set(theme_kp())

library(cluster)
library(factoextra)

pal_saturation = c("#CC79A7", "#E69F00", "#0072B2")
breaks_saturation = c("timezero", "drought", "d+rewet")

```

```{r}
targets::tar_load_everything()

subset_and_refactor_data = function(dat){
  dat %>% 
    filter(site == "Washington") %>% 
    filter(!length %in% "150d")  %>% 
    mutate(length = case_match(length, "30d" ~ "Day 30", "90d" ~ "Day 90", "1000d" ~ "Day 1000", "timezero" ~ "Day 0"),
           length = factor(length, levels = c("Day 0", "Day 30", "Day 90", "Day 1000")),
           saturation = factor(saturation, levels = c("timezero", "drought", "d+rewet")))
}
```

------

## FTICR

```{r fticr_data}

# subsetted FTICR data

fticr_long = fticr_long %>% subset_and_refactor_data(.)
fticr_relabund = fticr_relabund %>% subset_and_refactor_data(.)
fticr_relabund_trt = fticr_relabund_trt %>% subset_and_refactor_data(.)

```

```{r icr_relabund_wide}

relabund_wide = 
  fticr_relabund %>% 
  ungroup() %>% 
  mutate(Class = factor(Class, 
                        levels = c("aliphatic", "unsaturated/lignin", 
                                   "aromatic", "condensed aromatic"))) %>% 
  dplyr::select(-c(abund, total)) %>% 
  pivot_wider(names_from = "Class", values_from = "relabund") %>% 
  drop_na() %>% 
  force()

relabund_wide_surface = relabund_wide %>% filter(depth == "0-5cm")

```

### Stats -- PERMANOVA

```{r icr_permanova}

relabund_wide_no_t0 = 
  relabund_wide %>% 
  filter(length != "timezero") 

print("FTICR -- including top and bottom depths")

adonis2(relabund_wide_no_t0 %>% dplyr::select(where(is.numeric)) ~ 
          (depth+length+saturation+drying), 
        by = "margin",
        data = relabund_wide_no_t0) %>% broom::tidy() %>% knitr::kable()


print("FTICR -- including top depth only")

relabund_wide_surface_no_t0 = relabund_wide_no_t0 %>% filter(depth == "0-5cm")
adonis2(relabund_wide_surface_no_t0 %>% dplyr::select(where(is.numeric)) ~ 
          (length+saturation+drying), 
        by = "margin",
        data = relabund_wide_surface_no_t0) %>%  broom::tidy() %>% knitr::kable()

```


### Stats -- Clustering and NMDS --- formula

ignoring compound classes, doing clustering/NMDS based on individual molecules (presence/absence)


```{r}

fticr_wide = 
  fticr_long %>% 
  dplyr::select(coreID, DOC_ID, formula, presence, depth, site, drying, length, saturation) %>% 
  pivot_wider(names_from = "formula", values_from = "presence") %>% 
  janitor::remove_empty("cols") %>% 
  replace(is.na(.), 0)

```


```{r icr_mds_calc, include=FALSE}

num = 
  fticr_wide %>% 
  column_to_rownames("DOC_ID") %>% 
  dplyr::select(where(is.numeric)) %>%
  dplyr::mutate(row = row_number()) %>% 
  drop_na()

num_row_numbers = num %>% dplyr::select(row)

grp = 
  fticr_wide %>% 
  dplyr::select(!where(is.numeric)) %>% 
  dplyr::mutate(row = row_number())

set.seed(123456)
jacc = vegdist(num, method = "jaccard")
mds = metaMDS(jacc, k=3)

#scores(mds)

```


```{r icr_mds_output}

print(mds)
stressplot(mds)
plot(mds)

```

FTICR NMDS plots:

```{r icr_NMDS_plot}

scores = 
  as.data.frame(scores(mds)) %>% 
  rownames_to_column("DOC_ID") %>% 
  left_join(grp) %>% 
  force()

print("color by length")
ggplot(scores %>% filter(depth == "0-5cm"), 
       aes(x = NMDS1, y = NMDS2,
           fill = as.character(length),
           shape = saturation))+
  geom_point(size = 5, stroke = 1)+
  scale_shape_manual(values = c(21, 22, 23))+
  scale_fill_manual(values = pnw_palette("Bay", 5))+
  guides(fill = guide_legend(override.aes = list(shape = 21)))

print("color by saturation - top")
gg_icr_nmds_top = 
  ggplot(scores %>% filter(depth == "0-5cm"), 
       aes(x = NMDS1, y = NMDS2,
           color = as.character(saturation),
           size = length))+
  geom_point()+
#  labs(title = "FTICR NMDS - 0-5 cm")+
  scale_color_manual(values = pal_saturation,
                     breaks = breaks_saturation)+
  scale_shape_manual(values=c(15,16,17,18,19))+
  scale_size_manual(values=c(2,3,4,5,6))+
  theme(legend.position = "right")+
  #  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL

print("color by saturation - bottom")
gg_icr_nmds_btm = 
  ggplot(scores %>% filter(depth == "5cm-end"), 
       aes(x = NMDS1, y = NMDS2,
           color = as.character(saturation),
           size = length))+
  geom_point()+
#  labs(title = "FTICR NMDS - 5cm-end")+
  scale_color_manual(values = pal_saturation,
                     breaks = breaks_saturation)+
  scale_shape_manual(values=c(15,16,17,18,19))+
  scale_size_manual(values=c(2,3,4,5,6))+
  
  #  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL

gg_icr_nmds_top
gg_icr_nmds_btm

```


### Relative abundance

```{r icr_relabund_trt, fig.height=6, fig.width=18}

gg_icr_relabund = 
  fticr_relabund_trt %>% 
  group_by(site, depth, length, saturation, Class) %>% 
  dplyr::summarise(relabund = mean(relabund, na.omit = T)) %>% 
  ggplot(aes(x = length, y = relabund, fill = Class))+
  geom_bar(stat = "identity")+
  labs(x = "",
       y = "Relative Contribution (%)")+
  scale_fill_manual(values = whistledown_palette("sharmaji", 4))+
  facet_nested(depth ~ saturation, scale = "free_x", space = "free_x", nest_line = element_line(colour = "grey20"))+
  theme(legend.position = "right")

```

```{r icr_combined, fig.height=10, fig.width=10}
cowplot::plot_grid(gg_icr_nmds_top, gg_icr_relabund, 
                   ncol = 1, 
                   align = "hv", axis = "lr", 
                   rel_heights = c(1.2,2),
                   labels = c("A", "B"))
```




<details>
<summary> Click for relabund per core </summary>

```{r icr_relabund_cores, fig.height=12, fig.width=18}

fticr_relabund %>% 
  filter(depth == "0-5cm") %>% 
  ggplot(aes(x = coreID, y = relabund, fill = Class))+
  geom_bar(stat = "identity")+
  scale_fill_manual(values = whistledown_palette("sharmaji", 4))+
  facet_nested(. ~ site + depth + saturation + length, scale = "free_x", nest_line = element_line(colour = "grey20"))+
  theme(axis.text.x = element_text(angle = 90))

fticr_relabund %>% 
  filter(depth == "5cm-end") %>% 
  ggplot(aes(x = coreID, y = relabund, fill = Class))+
  geom_bar(stat = "identity")+
  scale_fill_manual(values = whistledown_palette("sharmaji", 4))+
  facet_nested(. ~ site + depth + saturation + length, scale = "free_x", nest_line = element_line(colour = "grey20"))+
  theme(axis.text.x = element_text(angle = 90))

```

</details>

------

------


## NMR

```{r nmr_data}

# subsetted FTICR data

nmr_relabundance = nmr_relabundance %>% subset_and_refactor_data(.)

```

### Stats -- PERMANOVA

```{r nmr_permanova}

nmr_relabund_wide = 
  nmr_relabundance %>% 
  #filter(length != "timezero") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "group", values_from = "relabund") %>% 
  force()

adonis2(nmr_relabund_wide %>% dplyr::select(where(is.numeric)) ~ 
            (length+saturation+drying), 
          by = "margin",
          data = nmr_relabund_wide) %>% 
  broom::tidy() %>% 
  knitr::kable()

```

### Stats -- PCA and clustering

<details>
  <summary> Click for details </summary>
  
```{r nmr_cluster}

df = nmr_relabund_wide %>%  dplyr::select(where(is.numeric))
grp = nmr_relabund_wide %>%  dplyr::select(!where(is.numeric))

fviz_nbclust(df, FUN = hcut, method = "wss")
fviz_nbclust(df, FUN = hcut, method = "silhouette")
# two clusters

d <- dist(df, method = "euclidean")
hc1 <- hclust(d, method = "complete" )
plot(hc1, cex = 0.6, hang = -1)
hc5 <- hclust(d, method = "ward.D2" )
sub_grp <- cutree(hc5, k = 2)
# table(sub_grp)
plot(hc5, cex = 0.6)
# rect.hclust(hc5, k = 5, border = 2:5)

df_cl <- mutate(df, cluster = sub_grp) %>% cbind(grp)

print("NMR hierarchical clustering: two clusters")
count(df_cl,cluster)

```

</details>

```{r pca_fn}
fit_pca_function = function(dat){
  
  dat %>% 
    drop_na()

  num = 
    dat %>%       
    dplyr::select(where(is.numeric)) %>%
    dplyr::mutate(row = row_number()) %>% 
    drop_na()
  
  num_row_numbers = num %>% dplyr::select(row)
  
  grp = 
    dat %>% 
    dplyr::select(!where(is.numeric)) %>% 
    dplyr::mutate(row = row_number()) %>% 
    right_join(num_row_numbers)
  
  
  num = num %>% dplyr::select(-row)
  pca_int = prcomp(num, scale. = T)
  
  list(num = num,
       grp = grp,
       pca_int = pca_int)
}
```

```{r nmr_pca_overall, fig.height=14, fig.width=12}

df_cl = df_cl %>% mutate(cluster = as.character(cluster)) 

library(ggConvexHull)

pca_cluster = fit_pca_function(df_cl) 

pca_length = 
  ggbiplot(pca_cluster$pca_int, obs.scale = 1, var.scale = 1,
         varname.size = 6,
         ellipse = T, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_convexhull(aes(group = pca_cluster$grp$cluster), 
                  color = "black",
                  linewidth = 1.2,
                  alpha = 0.1)+
  geom_point(size=5,stroke=1.5, alpha = 1, shape = 21,
             aes(fill = pca_cluster$grp$length))+ 
  #scale_shape_manual(values = c(23, 21, 22))+
  #scale_color_manual(values = pnw_palette("Sailboat", 7))+
  scale_fill_manual(values = pnw_palette("Bay", 5))+
  labs(title = "NMR PCA, color by length",
       subtitle = "Surface horizons only")+
  theme_kp()+
  ylim(-3, 3)+
  xlim(-4, 4)+
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL

pca_saturation = 
  ggbiplot(pca_cluster$pca_int, obs.scale = 1, var.scale = 1,
         varname.size = 6,
         ellipse = T, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_convexhull(aes(group = pca_cluster$grp$cluster), 
                  color = "black",
                  linewidth = 1.2,
                  alpha = 0.1)+
  geom_point(size=5,stroke=1.5, alpha = 1, shape = 21,
             aes(fill = pca_cluster$grp$saturation))+ 
  scale_fill_manual(values = pal_saturation,
                    breaks = breaks_saturation)+
  labs(title = "NMR PCA, color by saturation",
       subtitle = "Surface horizons only")+
  theme_kp()+
  ylim(-3, 3)+
  xlim(-4, 4)+
  guides(fill = guide_legend(override.aes = list(shape = 21)))+
  NULL

cowplot::plot_grid(pca_length, pca_saturation)

```

## NMR relabund

```{r nmr_relabund, fig.height=6, fig.width=10}

nmr_relabundance_summary = 
  nmr_relabundance %>% 
  group_by(site, depth, saturation, length, group) %>%
  dplyr::summarise(relabund = mean(relabund))

nmr_relabundance_summary %>% 
  ggplot(aes(x = length, y = relabund, fill = group))+
  geom_bar(stat = "identity")+
  facet_nested(. ~ site + depth + saturation, scale = "free_x", space = "free_x", nest_line = element_line(colour = "grey20"))+
  scale_fill_manual(values = whistledown_palette("queen", 5))+
  theme(axis.text.x = element_text(angle = 90))

```

<details>
  <summary> Click for Relative abundance by core </summary>
  
```{r nmr_relabund_cores, fig.height=12, fig.width=18}

print("relative abundance: Washington")

nmr_relabundance %>% 
  ggplot(aes(x = coreID, y = relabund, fill = group))+
  geom_bar(stat = "identity")+
  facet_nested(. ~ site + depth + saturation + length, scale = "free_x", nest_line = element_line(colour = "grey20"))+
  scale_fill_manual(values = whistledown_palette("queen", 5))+
  theme(axis.text.x = element_text(angle = 90))

```

</details>


## NMR spectra

```{r nmr_spectra}

nmr_spectra_processed %>% 
  filter(coreID %in% c("S92", "S32", "S53")) %>% 
  nmr_plot_spectra(
    binset = bins_Clemente2012,
    map = aes(group = coreID, x = ppm, y = intensity, color = saturation),
    stagger = 0.4,
    label_position = 2.3
  )+
  ylim(0, 2.5)+
  scale_color_manual(values = pal_saturation)

```


---

## Session Info 

<details>
  <summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>